// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKuxSF5UmGorM86MG6cg9ciBAzW9nD_Xk',
    appId: '1:747513263604:web:b564e867e20e3cfd9c35a1',
    messagingSenderId: '747513263604',
    projectId: 'macronutris',
    authDomain: 'macronutris.firebaseapp.com',
    databaseURL: 'https://macronutris-default-rtdb.firebaseio.com',
    storageBucket: 'macronutris.appspot.com',
    measurementId: 'G-7VLDGGYK28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_JIIOv-Da6dGOfrPMBUyJU6_tFIrZExw',
    appId: '1:747513263604:android:eaddba4f549ad8009c35a1',
    messagingSenderId: '747513263604',
    projectId: 'macronutris',
    databaseURL: 'https://macronutris-default-rtdb.firebaseio.com',
    storageBucket: 'macronutris.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVEz5MPYBDNTa8nX4GvVRopbp1E4pOHXw',
    appId: '1:747513263604:ios:1e997fcafa82b6739c35a1',
    messagingSenderId: '747513263604',
    projectId: 'macronutris',
    databaseURL: 'https://macronutris-default-rtdb.firebaseio.com',
    storageBucket: 'macronutris.appspot.com',
    iosClientId:
        '747513263604-ckj7kbrloiv8i8ipvsdf1vcfnutdonjn.apps.googleusercontent.com',
    iosBundleId: 'com.example.macroNutris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVEz5MPYBDNTa8nX4GvVRopbp1E4pOHXw',
    appId: '1:747513263604:ios:1e997fcafa82b6739c35a1',
    messagingSenderId: '747513263604',
    projectId: 'macronutris',
    databaseURL: 'https://macronutris-default-rtdb.firebaseio.com',
    storageBucket: 'macronutris.appspot.com',
    iosClientId:
        '747513263604-ckj7kbrloiv8i8ipvsdf1vcfnutdonjn.apps.googleusercontent.com',
    iosBundleId: 'com.example.macroNutris',
  );
}
